// AUTO-GENERATED by scripts/update-model-pricing.ts — DO NOT EDIT BY HAND.
// Source: /tmp/models.dev.json (anthropic provider).
// Regenerate: bun run scripts/update-model-pricing.ts
// Rates are USD per 1,000,000 tokens. cacheWrite5m is the 5-minute cache-write
// rate; the 1-hour rate is derived in model-pricing.ts as 2x input.

export type ModelCostRates = {
  input: number;
  output: number;
  cacheRead: number;
  cacheWrite5m: number;
};

export type ModelLimits = {
  contextWindow: number;
  maxOutputTokens: number;
};

export const MODEL_COST_RATES: Record<string, ModelCostRates> = {
  "claude-3-5-haiku-20241022": { input: 0.8, output: 4, cacheRead: 0.08, cacheWrite5m: 1 },
  "claude-3-5-haiku-latest": { input: 0.8, output: 4, cacheRead: 0.08, cacheWrite5m: 1 },
  "claude-3-5-sonnet-20240620": { input: 3, output: 15, cacheRead: 0.3, cacheWrite5m: 3.75 },
  "claude-3-5-sonnet-20241022": { input: 3, output: 15, cacheRead: 0.3, cacheWrite5m: 3.75 },
  "claude-3-7-sonnet-20250219": { input: 3, output: 15, cacheRead: 0.3, cacheWrite5m: 3.75 },
  "claude-3-haiku-20240307": { input: 0.25, output: 1.25, cacheRead: 0.03, cacheWrite5m: 0.3 },
  "claude-3-opus-20240229": { input: 15, output: 75, cacheRead: 1.5, cacheWrite5m: 18.75 },
  "claude-3-sonnet-20240229": { input: 3, output: 15, cacheRead: 0.3, cacheWrite5m: 0.3 },
  "claude-fable-5": { input: 10, output: 50, cacheRead: 1, cacheWrite5m: 12.5 },
  "claude-haiku-4-5": { input: 1, output: 5, cacheRead: 0.1, cacheWrite5m: 1.25 },
  "claude-haiku-4-5-20251001": { input: 1, output: 5, cacheRead: 0.1, cacheWrite5m: 1.25 },
  "claude-opus-4-0": { input: 15, output: 75, cacheRead: 1.5, cacheWrite5m: 18.75 },
  "claude-opus-4-1": { input: 15, output: 75, cacheRead: 1.5, cacheWrite5m: 18.75 },
  "claude-opus-4-1-20250805": { input: 15, output: 75, cacheRead: 1.5, cacheWrite5m: 18.75 },
  "claude-opus-4-20250514": { input: 15, output: 75, cacheRead: 1.5, cacheWrite5m: 18.75 },
  "claude-opus-4-5": { input: 5, output: 25, cacheRead: 0.5, cacheWrite5m: 6.25 },
  "claude-opus-4-5-20251101": { input: 5, output: 25, cacheRead: 0.5, cacheWrite5m: 6.25 },
  "claude-opus-4-6": { input: 5, output: 25, cacheRead: 0.5, cacheWrite5m: 6.25 },
  "claude-opus-4-7": { input: 5, output: 25, cacheRead: 0.5, cacheWrite5m: 6.25 },
  "claude-opus-4-8": { input: 5, output: 25, cacheRead: 0.5, cacheWrite5m: 6.25 },
  "claude-sonnet-4-0": { input: 3, output: 15, cacheRead: 0.3, cacheWrite5m: 3.75 },
  "claude-sonnet-4-20250514": { input: 3, output: 15, cacheRead: 0.3, cacheWrite5m: 3.75 },
  "claude-sonnet-4-5": { input: 3, output: 15, cacheRead: 0.3, cacheWrite5m: 3.75 },
  "claude-sonnet-4-5-20250929": { input: 3, output: 15, cacheRead: 0.3, cacheWrite5m: 3.75 },
  "claude-sonnet-4-6": { input: 3, output: 15, cacheRead: 0.3, cacheWrite5m: 3.75 },
};

export const MODEL_LIMITS: Record<string, ModelLimits> = {
  "claude-3-5-haiku-20241022": { contextWindow: 200000, maxOutputTokens: 8192 },
  "claude-3-5-haiku-latest": { contextWindow: 200000, maxOutputTokens: 8192 },
  "claude-3-5-sonnet-20240620": { contextWindow: 200000, maxOutputTokens: 8192 },
  "claude-3-5-sonnet-20241022": { contextWindow: 200000, maxOutputTokens: 8192 },
  "claude-3-7-sonnet-20250219": { contextWindow: 200000, maxOutputTokens: 64000 },
  "claude-3-haiku-20240307": { contextWindow: 200000, maxOutputTokens: 4096 },
  "claude-3-opus-20240229": { contextWindow: 200000, maxOutputTokens: 4096 },
  "claude-3-sonnet-20240229": { contextWindow: 200000, maxOutputTokens: 4096 },
  "claude-fable-5": { contextWindow: 1000000, maxOutputTokens: 128000 },
  "claude-haiku-4-5": { contextWindow: 200000, maxOutputTokens: 64000 },
  "claude-haiku-4-5-20251001": { contextWindow: 200000, maxOutputTokens: 64000 },
  "claude-opus-4-0": { contextWindow: 200000, maxOutputTokens: 32000 },
  "claude-opus-4-1": { contextWindow: 200000, maxOutputTokens: 32000 },
  "claude-opus-4-1-20250805": { contextWindow: 200000, maxOutputTokens: 32000 },
  "claude-opus-4-20250514": { contextWindow: 200000, maxOutputTokens: 32000 },
  "claude-opus-4-5": { contextWindow: 200000, maxOutputTokens: 64000 },
  "claude-opus-4-5-20251101": { contextWindow: 200000, maxOutputTokens: 64000 },
  "claude-opus-4-6": { contextWindow: 1000000, maxOutputTokens: 128000 },
  "claude-opus-4-7": { contextWindow: 1000000, maxOutputTokens: 128000 },
  "claude-opus-4-8": { contextWindow: 1000000, maxOutputTokens: 128000 },
  "claude-sonnet-4-0": { contextWindow: 200000, maxOutputTokens: 64000 },
  "claude-sonnet-4-20250514": { contextWindow: 200000, maxOutputTokens: 64000 },
  "claude-sonnet-4-5": { contextWindow: 200000, maxOutputTokens: 64000 },
  "claude-sonnet-4-5-20250929": { contextWindow: 200000, maxOutputTokens: 64000 },
  "claude-sonnet-4-6": { contextWindow: 1000000, maxOutputTokens: 64000 },
};

/** Short + family aliases pointing at the newest model in each family. */
export const MODEL_ALIASES: Record<string, string> = {
  "claude-fable": "claude-fable-5",
  "claude-haiku": "claude-haiku-4-5",
  "claude-opus": "claude-opus-4-8",
  "claude-sonnet": "claude-sonnet-4-6",
  "fable": "claude-fable-5",
  "haiku": "claude-haiku-4-5",
  "opus": "claude-opus-4-8",
  "sonnet": "claude-sonnet-4-6",
};
