/**
 * Cost computation for synthesized claude -p result events.
 *
 * The bridge drives the interactive TUI, whose transcript carries a token
 * `usage` breakdown but no `total_cost_usd`. We recompute cost from models.dev
 * rates (see model-pricing-data.ts, regenerated by scripts/update-model-pricing.ts).
 *
 * Anthropic bills cache writes by TTL: a 5-minute write is 1.25x base input
 * (the rate models.dev stores), a 1-hour write is 2x base input. The interactive
 * `usage.cache_creation` object carries the 5m/1h split, so the computed cost
 * matches Claude Code's headless `total_cost_usd` to the cent.
 */
import {
  MODEL_ALIASES,
  MODEL_COST_RATES,
  MODEL_LIMITS,
  type ModelCostRates,
  type ModelLimits,
} from "./model-pricing-data.ts";

/** Anthropic prices a 1-hour cache write at 2x base input. */
export const CACHE_WRITE_1H_MULTIPLIER = 2;

export type TokenUsage = {
  input_tokens?: number;
  output_tokens?: number;
  cache_read_input_tokens?: number;
  cache_creation_input_tokens?: number;
  cache_creation?: {
    ephemeral_5m_input_tokens?: number;
    ephemeral_1h_input_tokens?: number;
  };
  server_tool_use?: { web_search_requests?: number };
};

/**
 * Resolve a model identifier to its cost rates. Tries, in order: exact id,
 * alias (`opus`, `claude-opus`, ...), then a family substring fallback. A
 * trailing context-window suffix such as `[1m]` is stripped first.
 */
export function resolveModelCostRates(model: string | undefined): ModelCostRates | null {
  if (!model) return null;
  const key = model.trim().toLowerCase().replace(/\[[^\]]*\]\s*$/, "");
  if (!key) return null;

  const exact = MODEL_COST_RATES[key];
  if (exact) return exact;

  const aliased = MODEL_ALIASES[key];
  if (aliased && MODEL_COST_RATES[aliased]) return MODEL_COST_RATES[aliased]!;

  // Family fallback: an unknown id like "claude-opus-4-9" still contains "opus".
  for (const [alias, id] of Object.entries(MODEL_ALIASES)) {
    if (key.includes(alias) && MODEL_COST_RATES[id]) return MODEL_COST_RATES[id]!;
  }
  return null;
}

/**
 * Compute total cost in USD for a turn's token usage, or null when the model is
 * unknown or usage is missing. Mirrors Claude Code's headless `total_cost_usd`.
 */
export function computeCostUsd(model: string | undefined, usage: TokenUsage | undefined): number | null {
  const rates = resolveModelCostRates(model);
  if (!rates || !usage) return null;

  const input = usage.input_tokens ?? 0;
  const output = usage.output_tokens ?? 0;
  const cacheRead = usage.cache_read_input_tokens ?? 0;

  const detail = usage.cache_creation;
  const hasSplit =
    detail != null &&
    (detail.ephemeral_5m_input_tokens != null || detail.ephemeral_1h_input_tokens != null);
  const cacheWrite5m = hasSplit
    ? detail!.ephemeral_5m_input_tokens ?? 0
    : usage.cache_creation_input_tokens ?? 0;
  const cacheWrite1h = hasSplit ? detail!.ephemeral_1h_input_tokens ?? 0 : 0;

  const microUsd =
    input * rates.input +
    output * rates.output +
    cacheRead * rates.cacheRead +
    cacheWrite5m * rates.cacheWrite5m +
    cacheWrite1h * rates.input * CACHE_WRITE_1H_MULTIPLIER;

  return microUsd / 1_000_000;
}

export function resolveModelLimits(model: string | undefined): ModelLimits | null {
  if (!model) return null;
  const key = model.trim().toLowerCase().replace(/\[[^\]]*\]\s*$/, "");
  if (MODEL_LIMITS[key]) return MODEL_LIMITS[key]!;
  const aliased = MODEL_ALIASES[key];
  if (aliased && MODEL_LIMITS[aliased]) return MODEL_LIMITS[aliased]!;
  for (const [alias, id] of Object.entries(MODEL_ALIASES)) {
    if (key.includes(alias) && MODEL_LIMITS[id]) return MODEL_LIMITS[id]!;
  }
  return null;
}

/**
 * Best-effort reconstruction of Claude Code's headless `modelUsage` object,
 * keyed by model id. Token counts and cost are exact; contextWindow/
 * maxOutputTokens come from the models.dev snapshot (null when unknown).
 */
export function buildModelUsage(
  model: string | undefined,
  usage: TokenUsage | undefined
): Record<string, unknown> | null {
  if (!model || !usage) return null;
  const limits = resolveModelLimits(model);
  return {
    [model]: {
      inputTokens: usage.input_tokens ?? 0,
      outputTokens: usage.output_tokens ?? 0,
      cacheReadInputTokens: usage.cache_read_input_tokens ?? 0,
      cacheCreationInputTokens: usage.cache_creation_input_tokens ?? 0,
      webSearchRequests: usage.server_tool_use?.web_search_requests ?? 0,
      costUSD: computeCostUsd(model, usage) ?? 0,
      contextWindow: limits?.contextWindow ?? null,
      maxOutputTokens: limits?.maxOutputTokens ?? null,
    },
  };
}
